[sneakHeight]
eyeHeight = 1.54
hitboxHeight = 1.8
[movementInterpolation]
disableForSneaking = true
disableForHeads = true
[swordBlocking]
hideShields = false
hideOffhandSlot = false
animateSword = false
preventCombinedAnimation = true
fakeShield = false
[itemCooldowns]
disableEnderpearlCooldown = false
[poses]
disableCrouchToFit = true
disableCrawlToFit = true
disableSwimming = true
[worldLoadingBackgrounds]
disableNether = false
disableEnd = false
disableOther = false
[dangerZone]
disableOnNonHypixelServers = false
disableOnHypixelSMP = false
